<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, DejaVu Sans, sans-serif;
            color: #000;
            font-size: 11px;
            line-height: 1.3;
        }
        .center { text-align: center; }
        .company { font-size: 13px; font-weight: bold; }
        .title { font-size: 11px; font-weight: bold; margin: 4px 0; }
        .scale { font-style: italic; color: #333; margin-bottom: 15px; }
        
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th {
            font-weight: normal;
            text-align: right;
            border-bottom: 1px solid #000;
            padding: 2px 4px;
        }
        td {
            padding: 3px 4px;
            vertical-align: bottom;
        }
        .amount {
            text-align: right;
            width: 14%;
        }
        .section-title {
            font-weight: bold;
            padding-top: 8px;
        }
        .sub-section-title {
            padding-left: 12px;
            font-style: italic;
        }
        .indent-item { padding-left: 24px; }
        .total-row td {
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            font-weight: bold;
        }
        .final-row td {
            border-top: 1px solid #000;
            border-bottom: 4px double #000;
            font-weight: bold;
        }
    </style>
</head>
<body>

<div class="center">
    <div class="company">{{ $data['company'] }}</div>
    <div class="title">{{ $data['title'] }}</div>
    <div class="scale">{{ $data['scale'] }}</div>
</div>

<table>
    <thead>
        <tr>
            <th style="text-align: left; font-weight: bold;"></th>
            <th colspan="3" style="text-align: center; border-bottom: 1px solid #000; font-weight: bold;">Years ended</th>
        </tr>
        <tr>
            <th style="text-align: left;"></th>
            @foreach($data['dates'] as $date)
                <th style="font-weight: bold;">{{ $date }}</th>
            @endforeach
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="font-style: italic;">Cash, cash equivalents and restricted cash, beginning balances</td>
            @foreach($data['beginning_cash'] as $val)
                <td class="amount">${{ number_format($val) }}</td>
            @endforeach
        </tr>

        <tr>
            <td class="section-title">Operating activities:</td>
            <td></td><td></td><td></td>
        </tr>
        <tr>
            <td class="indent-item">Net income</td>
            @foreach($data['operating_net_income'] as $val)
                <td class="amount">{{ number_format($val) }}</td>
            @endforeach
        </tr>
        <tr>
            <td class="sub-section-title">Adjustments to reconcile net income to cash generated by operating activities:</td>
            <td></td><td></td><td></td>
        </tr>
        @foreach($data['operating_adjustments'] as $label => $values)
        <tr>
            <td class="indent-item">{{ $label }}</td>
            @foreach($values as $val)
                <td class="amount">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>
        @endforeach

        <tr>
            <td class="sub-section-title">Changes in operating assets and liabilities:</td>
            <td></td><td></td><td></td>
        </tr>
        @foreach($data['operating_changes'] as $label => $values)
        <tr>
            <td class="indent-item">{{ $label }}</td>
            @foreach($values as $val)
                <td class="amount">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>
        @endforeach
        <tr class="total-row">
            <td style="padding-left: 24px;">Cash generated by operating activities</td>
            @foreach($data['operating_total'] as $val)
                <td class="amount">{{ number_format($val) }}</td>
            @endforeach
        </tr>

        <tr>
            <td class="section-title">Investing activities:</td>
            <td></td><td></td><td></td>
        </tr>
        @foreach($data['investing_activities'] as $label => $values)
        <tr>
            <td class="indent-item">{{ $label }}</td>
            @foreach($values as $val)
                <td class="amount">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>
        @endforeach
        <tr class="total-row">
            <td style="padding-left: 24px;">Cash used in investing activities</td>
            @foreach($data['investing_total'] as $val)
                <td class="amount">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>

        <tr>
            <td class="section-title">Financing activities:</td>
            <td></td><td></td><td></td>
        </tr>
        @foreach($data['financing_activities'] as $label => $values)
        <tr>
            <td class="indent-item">{{ $label }}</td>
            @foreach($values as $val)
                <td class="amount">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>
        @endforeach
        <tr class="total-row">
            <td style="padding-left: 24px;">Cash used in financing activities</td>
            @foreach($data['financing_total'] as $val)
                <td class="amount">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>

        <tr>
            <td style="padding-top: 10px;">Decrease in cash, cash equivalents and restricted cash</td>
            @foreach($data['net_decrease'] as $val)
                <td class="amount" style="border-top: 1px solid #000;">{{ $val < 0 ? '('.number_format(abs($val)).')' : number_format($val) }}</td>
            @endforeach
        </tr>
        <tr class="final-row">
            <td>Cash, cash equivalents and restricted cash, ending balances</td>
            @foreach($data['ending_cash'] as $val)
                <td class="amount">${{ number_format($val) }}</td>
            @endforeach
        </tr>
    </tbody>
</table>

<div style="margin-top: 25px; font-weight: bold;">Supplemental cash flow disclosure:</div>
<table style="margin-top: 5px;">
    <tbody>
        @foreach($data['supplemental'] as $label => $values)
        <tr>
            <td style="width: 58%;">{{ $label }}</td>
            @foreach($values as $val)
                <td class="amount" style="border: none;">${{ number_format($val) }}</td>
            @endforeach
        </tr>
        @endforeach
    </tbody>
</table>

</body>
</html>